# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04sync\"*\n\x05Match\x12\x0e\n\x06random\x18\x01 \x01(\x08\x12\x11\n\tpickColor\x18\x02 \x01(\x05\"\x18\n\tMatchResp\x12\x0b\n\x03ret\x18\x01 \x01(\x08\"\r\n\x0b\x43\x61ncelMatch\"\x1e\n\x0f\x43\x61ncelMatchResp\x12\x0b\n\x03ret\x18\x01 \x01(\x08\",\n\x0fGameSetupNotify\x12\x19\n\x04side\x18\x01 \x01(\x0e\x32\x0b.sync.Color\"\x0b\n\tGameReady\"\x1c\n\rGameReadyResp\x12\x0b\n\x03ret\x18\x01 \x01(\x08\"_\n\tMovePiece\x12\x0f\n\x07originX\x18\x01 \x01(\x05\x12\x0f\n\x07originY\x18\x02 \x01(\x05\x12\t\n\x01X\x18\x03 \x01(\x05\x12\t\n\x01Y\x18\x04 \x01(\x05\x12\x1a\n\x05\x63olor\x18\x05 \x01(\x0e\x32\x0b.sync.Color\"\x17\n\x08MoveResp\x12\x0b\n\x03ret\x18\x01 \x01(\x08\",\n\x07Promote\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05*\x1d\n\x05\x43olor\x12\t\n\x05white\x10\x00\x12\t\n\x05\x62lack\x10\x01*K\n\tMessageID\x12\x0b\n\x07padding\x10\x00\x12\t\n\x05match\x10\x01\x12\x08\n\x04move\x10\x02\x12\x0f\n\x0b\x63\x61ncelMatch\x10\x03\x12\x0b\n\x07promote\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COLOR._serialized_start=394
  _COLOR._serialized_end=423
  _MESSAGEID._serialized_start=425
  _MESSAGEID._serialized_end=500
  _MATCH._serialized_start=20
  _MATCH._serialized_end=62
  _MATCHRESP._serialized_start=64
  _MATCHRESP._serialized_end=88
  _CANCELMATCH._serialized_start=90
  _CANCELMATCH._serialized_end=103
  _CANCELMATCHRESP._serialized_start=105
  _CANCELMATCHRESP._serialized_end=135
  _GAMESETUPNOTIFY._serialized_start=137
  _GAMESETUPNOTIFY._serialized_end=181
  _GAMEREADY._serialized_start=183
  _GAMEREADY._serialized_end=194
  _GAMEREADYRESP._serialized_start=196
  _GAMEREADYRESP._serialized_end=224
  _MOVEPIECE._serialized_start=226
  _MOVEPIECE._serialized_end=321
  _MOVERESP._serialized_start=323
  _MOVERESP._serialized_end=346
  _PROMOTE._serialized_start=348
  _PROMOTE._serialized_end=392
# @@protoc_insertion_point(module_scope)
